default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432

development:
  <<: *default
  database: factorial_development

test:
  <<: *default
  database: factorial_test
  password: postgres
  user: postgres

# Redis configuration
redis:
  host: localhost
  port: 6379
  db: 0