name: Ruby Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: factorial_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
      redis:
        image: redis:6
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.4.2'
        bundler-cache: true
    
    - name: Install dependencies
      run: bundle install
      
    - name: Setup database
      run: |
        PGPASSWORD=postgres psql -h localhost -U postgres -d factorial_test -f database/schema.sql
      env:
        PGPASSWORD: postgres
        
    - name: Run tests
      run: bundle exec rspec
      env:
        RAILS_ENV: test
        REDIS_URL: redis://localhost:6379/0
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/factorial_test
